//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKOffice.RestService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderConfirmation", Namespace="http://schemas.datacontract.org/2004/07/WcfService.domain.order")]
    [System.SerializableAttribute()]
    public partial class OrderConfirmation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] AltDeliveryInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlternativeNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SKOffice.RestService.OrderCategory[] CategoriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] CompanyInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] CustomerInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SKOffice.RestService.OrderNote[] NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OrderDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ProducedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WeekField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] kitchenInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] AltDeliveryInfo {
            get {
                return this.AltDeliveryInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.AltDeliveryInfoField, value) != true)) {
                    this.AltDeliveryInfoField = value;
                    this.RaisePropertyChanged("AltDeliveryInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlternativeNumber {
            get {
                return this.AlternativeNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AlternativeNumberField, value) != true)) {
                    this.AlternativeNumberField = value;
                    this.RaisePropertyChanged("AlternativeNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SKOffice.RestService.OrderCategory[] Categories {
            get {
                return this.CategoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriesField, value) != true)) {
                    this.CategoriesField = value;
                    this.RaisePropertyChanged("Categories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] CompanyInfo {
            get {
                return this.CompanyInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyInfoField, value) != true)) {
                    this.CompanyInfoField = value;
                    this.RaisePropertyChanged("CompanyInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] CustomerInfo {
            get {
                return this.CustomerInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerInfoField, value) != true)) {
                    this.CustomerInfoField = value;
                    this.RaisePropertyChanged("CustomerInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SKOffice.RestService.OrderNote[] Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((this.OrderDateField.Equals(value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderName {
            get {
                return this.OrderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderNameField, value) != true)) {
                    this.OrderNameField = value;
                    this.RaisePropertyChanged("OrderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderNumber {
            get {
                return this.OrderNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderNumberField, value) != true)) {
                    this.OrderNumberField = value;
                    this.RaisePropertyChanged("OrderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ProducedDate {
            get {
                return this.ProducedDateField;
            }
            set {
                if ((this.ProducedDateField.Equals(value) != true)) {
                    this.ProducedDateField = value;
                    this.RaisePropertyChanged("ProducedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Week {
            get {
                return this.WeekField;
            }
            set {
                if ((object.ReferenceEquals(this.WeekField, value) != true)) {
                    this.WeekField = value;
                    this.RaisePropertyChanged("Week");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] kitchenInfo {
            get {
                return this.kitchenInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.kitchenInfoField, value) != true)) {
                    this.kitchenInfoField = value;
                    this.RaisePropertyChanged("kitchenInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderCategory", Namespace="http://schemas.datacontract.org/2004/07/WcfService.domain.order")]
    [System.SerializableAttribute()]
    public partial class OrderCategory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SKOffice.RestService.OrderElement[] ElementsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SKOffice.RestService.OrderElement[] Elements {
            get {
                return this.ElementsField;
            }
            set {
                if ((object.ReferenceEquals(this.ElementsField, value) != true)) {
                    this.ElementsField = value;
                    this.RaisePropertyChanged("Elements");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderNote", Namespace="http://schemas.datacontract.org/2004/07/WcfService.domain.order")]
    [System.SerializableAttribute()]
    public partial class OrderNote : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderElement", Namespace="http://schemas.datacontract.org/2004/07/WcfService.domain.order")]
    [System.SerializableAttribute()]
    public partial class OrderElement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ElementInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FinishField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HingeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((object.ReferenceEquals(this.AmountField, value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ElementInfo {
            get {
                return this.ElementInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ElementInfoField, value) != true)) {
                    this.ElementInfoField = value;
                    this.RaisePropertyChanged("ElementInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Finish {
            get {
                return this.FinishField;
            }
            set {
                if ((object.ReferenceEquals(this.FinishField, value) != true)) {
                    this.FinishField = value;
                    this.RaisePropertyChanged("Finish");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hinge {
            get {
                return this.HingeField;
            }
            set {
                if ((object.ReferenceEquals(this.HingeField, value) != true)) {
                    this.HingeField = value;
                    this.RaisePropertyChanged("Hinge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Position {
            get {
                return this.PositionField;
            }
            set {
                if ((object.ReferenceEquals(this.PositionField, value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unit {
            get {
                return this.UnitField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitField, value) != true)) {
                    this.UnitField = value;
                    this.RaisePropertyChanged("Unit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RestService.IRestService")]
    public interface IRestService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/getOrder", ReplyAction="http://tempuri.org/IRestService/getOrderResponse")]
        SKOffice.RestService.OrderConfirmation getOrder(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/getOrder", ReplyAction="http://tempuri.org/IRestService/getOrderResponse")]
        System.Threading.Tasks.Task<SKOffice.RestService.OrderConfirmation> getOrderAsync(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/getAllActiveOrders", ReplyAction="http://tempuri.org/IRestService/getAllActiveOrdersResponse")]
        SKOffice.RestService.OrderConfirmation[] getAllActiveOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/getAllActiveOrders", ReplyAction="http://tempuri.org/IRestService/getAllActiveOrdersResponse")]
        System.Threading.Tasks.Task<SKOffice.RestService.OrderConfirmation[]> getAllActiveOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/addOrderConfirmation", ReplyAction="http://tempuri.org/IRestService/addOrderConfirmationResponse")]
        bool addOrderConfirmation(string[] fileContent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/addOrderConfirmation", ReplyAction="http://tempuri.org/IRestService/addOrderConfirmationResponse")]
        System.Threading.Tasks.Task<bool> addOrderConfirmationAsync(string[] fileContent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/addNote", ReplyAction="http://tempuri.org/IRestService/addNoteResponse")]
        bool addNote(string text, string orderNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/addNote", ReplyAction="http://tempuri.org/IRestService/addNoteResponse")]
        System.Threading.Tasks.Task<bool> addNoteAsync(string text, string orderNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRestServiceChannel : SKOffice.RestService.IRestService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RestServiceClient : System.ServiceModel.ClientBase<SKOffice.RestService.IRestService>, SKOffice.RestService.IRestService {
        
        public RestServiceClient() {
        }
        
        public RestServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RestServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SKOffice.RestService.OrderConfirmation getOrder(string fileName) {
            return base.Channel.getOrder(fileName);
        }
        
        public System.Threading.Tasks.Task<SKOffice.RestService.OrderConfirmation> getOrderAsync(string fileName) {
            return base.Channel.getOrderAsync(fileName);
        }
        
        public SKOffice.RestService.OrderConfirmation[] getAllActiveOrders() {
            return base.Channel.getAllActiveOrders();
        }
        
        public System.Threading.Tasks.Task<SKOffice.RestService.OrderConfirmation[]> getAllActiveOrdersAsync() {
            return base.Channel.getAllActiveOrdersAsync();
        }
        
        public bool addOrderConfirmation(string[] fileContent) {
            return base.Channel.addOrderConfirmation(fileContent);
        }
        
        public System.Threading.Tasks.Task<bool> addOrderConfirmationAsync(string[] fileContent) {
            return base.Channel.addOrderConfirmationAsync(fileContent);
        }
        
        public bool addNote(string text, string orderNumber) {
            return base.Channel.addNote(text, orderNumber);
        }
        
        public System.Threading.Tasks.Task<bool> addNoteAsync(string text, string orderNumber) {
            return base.Channel.addNoteAsync(text, orderNumber);
        }
    }
}
